version: "3.1"

services:
  nginx:
    image: nginx
    restart: always
    container_name: reverse_proxy
    volumes:
     - "/etc/pswd:/etc/nginx/password"
     - "/var/log/nginx:/var/log/nginx:rw"
     - "./snippets:/etc/nginx/snippets:ro"
     - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
     - "certs:/etc/letsencrypt"
     - "acme_challenge:/var/www/letsencrypt"
    expose:
     - 81
    ports:
     - "80:80"
     - "443:443"
    environment:
      DOLLAR: '$$'
    command: ["/bin/bash", "-c", "rm -rf /var/log/nginx/* && nginx -g 'daemon off;'"]
    networks:
      server:
        aliases:
         - loadbalancer
  certbot:
    build: ./certbot
    restart: always
    container_name: certbot
    volumes:
     - "certs:/etc/letsencrypt"
     - "acme_challenge:/var/www/letsencrypt"
     - "/var/log/letsencrypt:/var/log/letsencrypt"

networks:
  server:
    external:
      name: server

volumes:
  certs:
    external: true
  acme_challenge:
